import { z } from "zod";
import {
  CHOICE_TYPES,
  DEFAULT_LAYOUT,
  DEFAULT_LOCALE,
  QUESTIONNAIRE_LAYOUTS,
  QUESTION_TYPES,
  RATING_TYPES,
  SUPPORTED_LOCALES,
} from "@/lib/questionnaire/types";
import { locationIdSchema } from "./location";

const uuid = z.string().uuid();
const localeCodes = SUPPORTED_LOCALES.map((l) => l.code) as [string, ...string[]];
const localeCode = z.enum(localeCodes);

/** { en: "...", am: "..." } — empty strings are dropped; the default locale is enforced separately. */
const localized = (max: number) =>
  z
    .partialRecord(localeCode, z.string().trim().max(max))
    .transform((r): Record<string, string> =>
      Object.fromEntries(Object.entries(r).filter((e): e is [string, string] => !!e[1])),
    );

const configSchema = z
  .object({
    scale: z.number().int().min(3).max(10).optional(),
    min: z.number().finite().optional(),
    max: z.number().finite().optional(),
    integer: z.boolean().optional(),
    minLength: z.number().int().min(0).max(2000).optional(),
    maxLength: z.number().int().min(1).max(2000).optional(),
    minSelect: z.number().int().min(0).max(50).optional(),
    maxSelect: z.number().int().min(1).max(50).optional(),
  })
  .strict();

export const optionInputSchema = z.object({
  /** kept when editing so historical answers stay meaningful; generated for new options */
  value: z
    .string()
    .regex(/^[a-z0-9_-]{1,40}$/i)
    .optional(),
  label: localized(120),
});

export const questionInputSchema = z
  .object({
    type: z.enum(QUESTION_TYPES),
    text: localized(300),
    description: localized(500).optional(),
    placeholder: localized(120).optional(),
    config: configSchema.default({}),
    options: z.array(optionInputSchema).max(30).default([]),
    isActive: z.boolean().default(true),
  })
  .superRefine((q, ctx) => {
    if (!q.text[DEFAULT_LOCALE]) {
      ctx.addIssue({ code: "custom", path: ["text"], message: "Question text (English) is required." });
    }
    const isChoice = CHOICE_TYPES.includes(q.type);
    if (isChoice) {
      if (q.options.length < 2)
        ctx.addIssue({ code: "custom", path: ["options"], message: "Add at least two options." });
      q.options.forEach((o, i) => {
        if (!o.label[DEFAULT_LOCALE]) {
          ctx.addIssue({
            code: "custom",
            path: ["options", i],
            message: "Option label (English) is required.",
          });
        }
      });
    } else if (q.options.length > 0) {
      ctx.addIssue({ code: "custom", path: ["options"], message: "This question type has no options." });
    }
    const c = q.config;
    if (c.min !== undefined && c.max !== undefined && c.min > c.max) {
      ctx.addIssue({ code: "custom", path: ["config", "min"], message: "Minimum cannot exceed maximum." });
    }
    if (c.minLength !== undefined && c.maxLength !== undefined && c.minLength > c.maxLength) {
      ctx.addIssue({
        code: "custom",
        path: ["config", "minLength"],
        message: "Minimum cannot exceed maximum.",
      });
    }
    if (c.minSelect !== undefined && c.maxSelect !== undefined && c.minSelect > c.maxSelect) {
      ctx.addIssue({
        code: "custom",
        path: ["config", "minSelect"],
        message: "Minimum cannot exceed maximum.",
      });
    }
  });

const visibilityRuleSchema = z.object({
  questionRef: uuid,
  operator: z.enum(["equals", "not_equals", "in", "gte", "lte", "answered"]),
  value: z.union([z.string().max(100), z.number().finite(), z.array(z.string().max(100)).max(30)]).optional(),
});

export const visibilitySchema = z
  .object({ match: z.enum(["all", "any"]), rules: z.array(visibilityRuleSchema).min(1).max(10) })
  .nullable();

export const questionnaireMetaSchema = z
  .object({
    title: localized(150),
    description: localized(500).optional(),
    defaultLocale: localeCode.default(DEFAULT_LOCALE),
    locales: z.array(localeCode).min(1).default([DEFAULT_LOCALE]),
    collectContact: z.boolean().default(false),
    layout: z.enum(QUESTIONNAIRE_LAYOUTS).default(DEFAULT_LAYOUT),
  })
  .superRefine((m, ctx) => {
    if (!m.title[m.defaultLocale]) {
      ctx.addIssue({
        code: "custom",
        path: ["title"],
        message: "A title in the default language is required.",
      });
    }
    if (!m.locales.includes(m.defaultLocale)) {
      ctx.addIssue({ code: "custom", path: ["locales"], message: "The default language must be enabled." });
    }
  });

export const draftQuestionSchema = z.object({
  /** stable reference (QuestionnaireQuestion.id); generated by the client for new items */
  ref: uuid,
  questionId: uuid,
  isRequired: z.boolean().default(false),
  isActive: z.boolean().default(true),
  isPrimaryRating: z.boolean().default(false),
  visibility: visibilitySchema.default(null),
});

export const draftSchema = z
  .object({
    meta: questionnaireMetaSchema,
    questions: z.array(draftQuestionSchema).max(200),
  })
  .superRefine((d, ctx) => {
    const seenRefs = new Set<string>();
    let primary = 0;
    d.questions.forEach((q, i) => {
      if (seenRefs.has(q.ref))
        ctx.addIssue({ code: "custom", path: ["questions", i], message: "Duplicate item." });
      // conditional logic may only look backwards: no cycles, no forward references
      for (const r of q.visibility?.rules ?? []) {
        if (!seenRefs.has(r.questionRef)) {
          ctx.addIssue({
            code: "custom",
            path: ["questions", i, "visibility"],
            message: "A condition can only depend on a question that appears before it.",
          });
        }
      }
      if (q.isPrimaryRating) primary++;
      seenRefs.add(q.ref);
    });
    if (primary > 1)
      ctx.addIssue({
        code: "custom",
        path: ["questions"],
        message: "Only one question can be the overall rating.",
      });
  });

export const assignmentTargetSchema = z
  .object({
    scopeType: z.enum(["ALL", "DISTRICT", "BRANCH", "DEPARTMENT"]),
    id: locationIdSchema.optional(),
  })
  .superRefine((t, ctx) => {
    if (t.scopeType === "ALL" && t.id)
      ctx.addIssue({ code: "custom", path: ["id"], message: "Not allowed for bank-wide." });
    if (t.scopeType !== "ALL" && !t.id)
      ctx.addIssue({ code: "custom", path: ["id"], message: "Select a location." });
  });
export const assignmentsSchema = z.array(assignmentTargetSchema).max(200);

export type QuestionInput = z.infer<typeof questionInputSchema>;
export type QuestionnaireMetaInput = z.infer<typeof questionnaireMetaSchema>;
export type DraftInput = z.infer<typeof draftSchema>;
export type AssignmentTarget = z.infer<typeof assignmentTargetSchema>;

export { RATING_TYPES };
